FROM alphacep/kaldi-vosk-server:latest

ENV MODEL_VERSION 0.2

RUN mkdir /opt/vosk-model-en

COPY model_english.tgz /opt/vosk-model-en/

RUN cd /opt/vosk-model-en \
   && tar -xvzf model_english.tgz

ARG buildtime_variable=8000
ENV VOSK_SAMPLE_RATE=$buildtime_variable

EXPOSE 2700
WORKDIR /opt/vosk-server/websocket
CMD [ "python3", "./asr_server.py", "/opt/vosk-model-en/model" ]
